name: Artifacts
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          #Кэшировать скачанные pip пакеты между запусками
          cache: "pip"
      - name: Установка зависимостей
        run: |
          pip install -r requirements.txt
      - name: Создать отчет
        run: |
          date > report.txt
          pip list >> report.txt
      - name: Сохранить отчет как артефакт
        uses: actions/upload-artifact@v4
        with:
          name: report        # имя архива для скачивания
          path: report.txt    # какой файл или папку сохранить
          retention-days: 7   # Хранить артефакт 7 дней (по умолчанию 90 дней)






          



          