name: Secrets
on: [push, workflow_dispatch]
permissions:
    contents: read

jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            - name: Переменная
              env:
                GREETING: ${{ vars.GREETING }}
              run: |
                echo "Приветствие: $GREETING"
            - name: Секрет
              env:
                TOKEN: ${{ secrets.API_TOKEN }}
              run: |
                # -n = "строка не пустая"; ${#TOKEN} = длинна строки
                if [ -n "${TOKEN}" ]; then
                    echo "Секрет на месте и его длина ${#TOKEN}"
                else
                    echo "Секрет не задан"
                    exit 1
                fi    
            - name: Только для main
            # Условие проверяет GitHub; фигурные скобки в if можно не писать
                if: github.ref_name == 'main'
                run: |
                    echo "Этоn шаг выполнится только на ветке main"